name: power_electronics
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - matplotlib
  - pandas
  - numpy
  - scipy
  - openai>=1.16.1
  - pip
  - pip:
    - pyspice==1.5
    - ollama  # Optional, for local models

